/**
 * This file is generated by scripts/generate-bundled-shards.mjs.
 * Do not edit manually.
 */
import type { StoredFoodItem } from '../sync/adapters/jsonShardedDatabaseAdapter'

import shard0000_json from '../../database/fdc/shards/0000.json'

export const bundledShards: Record<string, StoredFoodItem[]> = {
  '0000.json': shard0000_json as StoredFoodItem[]
}

export const bundledIndex = {
  shards: [
    {
      shard: '0000.json',
      size: 47
    }
  ],
  lastUpdated: '2026-03-20T09:30:21.120Z'
} as const
