name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - chore/**
      - feature/**
      - fix/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build (non-minified)
        run: BUILD_MINIFY=false npm run build

      - name: Bundle size check
        run: npm run check:bundle
